/**
 * Regenerate INDEX.md in every folder, or check the structure with --check.
 *
 * Rules: every non-hidden folder has a README.md starting with "# Title" and a generated INDEX.md;
 * blog folders at the root are NN-slug/; files inside them are NN-slug.ext with unique numbers.
 * Usage: node scripts/node/build-index.mjs [--check]   (exit 0 ok, 1 fail)
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = process.cwd();
const CHECK = process.argv.includes('--check');
const NUMBERED = /^(\d{2})-[a-z0-9]+(?:-[a-z0-9]+)*(?:\.[a-z0-9]+)?$/;
const SKIP = new Set(['README.md', 'INDEX.md']);
const errors = [];
let written = 0;

const title = (path) => {
  const text = readFileSync(path, 'utf8');
  const h1 = text.match(/^# (.+)$/m);
  if (h1) return h1[1].trim();
  const jsdoc = text.match(/^\/\*\*?\s*\n?\s*\*?\s*(\S.*)$/m);
  return jsdoc ? jsdoc[1].trim() : '';
};

function walk(dir) {
  const rel = relative(ROOT, dir).replaceAll('\\', '/') || '.';
  const entries = readdirSync(dir, { withFileTypes: true }).filter((e) => !e.name.startsWith('.') && !(rel === 'logs' && e.name.endsWith('.jsonl'))); // logs/*.jsonl are gitignored
  const readme = join(dir, 'README.md');
  if (!existsSync(readme)) errors.push(`${rel}: missing README.md`);
  else if (!/^# \S/.test(readFileSync(readme, 'utf8'))) errors.push(`${rel}/README.md: must start with "# Title"`);

  const docSection = rel.match(/^docs\/(\d{2})-/);
  const isBlogFolder = /^\d{2}-[^/]*$/.test(rel);
  const seen = new Map();
  for (const e of entries) {
    if (SKIP.has(e.name)) continue;
    let pattern = null;
    if (rel === '.' && e.isDirectory() && !['docs', 'logs', 'memory', 'scripts'].includes(e.name)) pattern = NUMBERED;
    else if (isBlogFolder && e.isFile()) pattern = NUMBERED;
    else if (rel === 'docs') pattern = e.isDirectory() ? NUMBERED : null;
    else if (docSection && e.isFile()) pattern = new RegExp(`^(${docSection[1]}-\\d{2})-[a-z0-9]+(?:-[a-z0-9]+)*\\.md$`);
    if (rel === 'docs' && e.isFile()) errors.push(`docs/${e.name}: docs/ holds only section folders`);
    if (!pattern) continue;
    const m = e.name.match(pattern);
    if (!m) { errors.push(`${rel}/${e.name}: expected ${docSection ? `${docSection[1]}-MM-slug.md` : 'NN-kebab-slug'}`); continue; }
    if (seen.has(m[1])) errors.push(`${rel}: number ${m[1]} used by ${seen.get(m[1])} and ${e.name}`);
    seen.set(m[1], e.name);
  }

  const rows = entries
    .filter((e) => !SKIP.has(e.name))
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((e) => {
      const link = e.isDirectory() ? `${e.name}/README.md` : e.name;
      const t = e.isDirectory()
        ? (existsSync(join(dir, e.name, 'README.md')) ? title(join(dir, e.name, 'README.md')) : '')
        : (/\.(md|mjs|js|css)$/.test(e.name) ? title(join(dir, e.name)) : '');
      return `| [${e.name}${e.isDirectory() ? '/' : ''}](${link}) | ${t} |`;
    });
  const index = `# Index\n\nGenerated by \`scripts/node/build-index.mjs\`. Do not edit by hand.\n\n| Item | Title |\n| :-- | :-- |\n${rows.join('\n')}\n`;
  const indexPath = join(dir, 'INDEX.md');
  const current = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : '';
  if (current !== index) {
    if (CHECK) errors.push(`${rel}/INDEX.md: stale (run build-index.mjs)`);
    else { writeFileSync(indexPath, index); written++; }
  }

  for (const e of entries) if (e.isDirectory()) walk(join(dir, e.name));
}

walk(ROOT);
for (const e of errors) console.log(`- ${e}`);
if (CHECK) {
  console.log(errors.length ? 'STRUCTURE-CHECK: FAIL' : 'STRUCTURE-CHECK: PASS');
} else {
  console.log(`INDEX: ${written} written`);
}
process.exit(errors.length ? 1 : 0);
